insertAtHead(head, 50);
  // std::cout << "Inserted at head 50: " << '\n';
  // insertAtHead(head, 40);
  // std::cout << "Inserted at head 40: " << '\n';
  // insertAtHead(head, 30);
  // std::cout << "Inserted at head 30: " << '\n';

  // insertAtTail(head, 60);
  // std::cout << "Inserted at tail 60: " << '\n';
  // insertAtTail(head, 70);
  // std::cout << "Inserted at tail 70: " << '\n';
  // insertAtTail(head, 80);
  // std::cout << "Inserted at tail 80: " << '\n';
  // insertAtTail(head, 90);
  // std::cout << "Inserted at tail 90: " << '\n';
  // insertAtTail(head, 20);
  // std::cout << "Inserted at tail 20: " << '\n';
  // insertAtTail(head, 10);
  // std::cout << "Inserted at tail 10: " << '\n';
  // insertAtTail(head, 100);
  // std::cout << "Inserted at tail 100: " << '\n';